// <auto-generated />
using System;
using ChessPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace kursProjChesh_Torgovcev.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    [Migration("20260409145957_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("ChessPlatform.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_game");

                    b.Property<int>("BlackPlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_black_player");

                    b.Property<int>("BlackTimeRemaining")
                        .HasColumnType("INTEGER")
                        .HasColumnName("black_time_remaining");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentFEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_fen");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<DateTime?>("LastMoveAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_move_at");

                    b.Property<string>("PGN")
                        .HasColumnType("TEXT")
                        .HasColumnName("pgn");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TimeControlIncrement")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_control_increment");

                    b.Property<int>("TimeControlMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_control_minutes");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_tournament");

                    b.Property<int?>("TournamentRound")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tournament_round");

                    b.Property<int>("WhitePlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_white_player");

                    b.Property<int>("WhiteTimeRemaining")
                        .HasColumnType("INTEGER")
                        .HasColumnName("white_time_remaining");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_winner");

                    b.HasKey("Id");

                    b.HasIndex("BlackPlayerId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WhitePlayerId");

                    b.HasIndex("WinnerId");

                    b.ToTable("game");
                });

            modelBuilder.Entity("ChessPlatform.Models.GameMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_move");

                    b.Property<string>("FENAfterMove")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("fen_after_move");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_game");

                    b.Property<DateTime>("MadeAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("made_at");

                    b.Property<string>("MoveNotation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("move_notation");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("move_number");

                    b.Property<string>("PlayerColor")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("player_color");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("game_move");
                });

            modelBuilder.Entity("ChessPlatform.Models.RatingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_history");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_game");

                    b.Property<int>("NewRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_rating");

                    b.Property<int>("OldRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("old_rating");

                    b.Property<int>("RatingChange")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating_change");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_user");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("rating_history");
                });

            modelBuilder.Entity("ChessPlatform.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_tournament");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_creator");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_participants");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_participants");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TimeControlMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_control_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int?>("TotalRounds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_rounds");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_winner");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("WinnerId");

                    b.ToTable("tournament");
                });

            modelBuilder.Entity("ChessPlatform.Models.TournamentMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_match");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_game");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_final");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("match_number");

                    b.Property<int?>("NextMatchId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_next_match");

                    b.Property<int?>("Player1Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_player1");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_player2");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round_number");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_tournament");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_winner");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("NextMatchId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WinnerId");

                    b.ToTable("tournament_match");
                });

            modelBuilder.Entity("ChessPlatform.Models.TournamentParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_participant");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("registered_at");

                    b.Property<int?>("SeedNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seed_number");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_tournament");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_user");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TournamentId", "UserId")
                        .IsUnique();

                    b.ToTable("tournament_participant");
                });

            modelBuilder.Entity("ChessPlatform.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_user");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Draws")
                        .HasColumnType("INTEGER")
                        .HasColumnName("draws");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("games_played");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastOnlineAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_online_at");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("losses");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_account");
                });

            modelBuilder.Entity("ChessPlatform.Models.Game", b =>
                {
                    b.HasOne("ChessPlatform.Models.User", "BlackPlayer")
                        .WithMany("GamesAsBlack")
                        .HasForeignKey("BlackPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChessPlatform.Models.Tournament", "Tournament")
                        .WithMany("Games")
                        .HasForeignKey("TournamentId");

                    b.HasOne("ChessPlatform.Models.User", "WhitePlayer")
                        .WithMany("GamesAsWhite")
                        .HasForeignKey("WhitePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChessPlatform.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BlackPlayer");

                    b.Navigation("Tournament");

                    b.Navigation("WhitePlayer");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("ChessPlatform.Models.GameMove", b =>
                {
                    b.HasOne("ChessPlatform.Models.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChessPlatform.Models.RatingHistory", b =>
                {
                    b.HasOne("ChessPlatform.Models.Game", "Game")
                        .WithMany("RatingHistories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChessPlatform.Models.User", "User")
                        .WithMany("RatingChanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChessPlatform.Models.Tournament", b =>
                {
                    b.HasOne("ChessPlatform.Models.User", "Creator")
                        .WithMany("CreatedTournaments")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChessPlatform.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("ChessPlatform.Models.TournamentMatch", b =>
                {
                    b.HasOne("ChessPlatform.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("ChessPlatform.Models.TournamentMatch", "NextMatch")
                        .WithMany()
                        .HasForeignKey("NextMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChessPlatform.Models.User", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id");

                    b.HasOne("ChessPlatform.Models.User", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id");

                    b.HasOne("ChessPlatform.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChessPlatform.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Game");

                    b.Navigation("NextMatch");

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Tournament");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("ChessPlatform.Models.TournamentParticipant", b =>
                {
                    b.HasOne("ChessPlatform.Models.Tournament", "Tournament")
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChessPlatform.Models.User", "User")
                        .WithMany("TournamentParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChessPlatform.Models.Game", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("RatingHistories");
                });

            modelBuilder.Entity("ChessPlatform.Models.Tournament", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Matches");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ChessPlatform.Models.User", b =>
                {
                    b.Navigation("CreatedTournaments");

                    b.Navigation("GamesAsBlack");

                    b.Navigation("GamesAsWhite");

                    b.Navigation("RatingChanges");

                    b.Navigation("TournamentParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
